### ISSUE TITLE
Docker Fails

### ISSUE THREAD

**Issue by halfagascan** [r3-team/r3_docker#2]
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
Linux tvh2 6.1.0-rpi6-rpi-v8  aarch64 GNU/Linux

`=> ERROR [r3 5/5] RUN tar -xvf REI3_3.2_arm64_linux.tar.gz r3 config_template.json  && sed -i "s/localhost/r3_db/g" config_template.json  && sed -i "s/443/80/g" co  5.5s '                                                                            
 ' [r3 5/5] RUN tar -xvf REI3_3.2_arm64_linux.tar.gz r3 config_template.json    && sed -i "s/localhost/r3_db/g" config_template.json    && sed -i "s/443/80/g" config_template.json        && chmod 755 r3 && chmod 644 config_template.json       && rm REI3_3.2_arm64_linux.tar.gz: '                                                                
'3.108 3.108 gzip: stdin: not in gzip format 3.110 tar: Child returned status 1 3.112 tar: Error is not recoverable: exiting now'
------
'failed to solve: process "/bin/sh -c tar -xvf REI3_${r3_version}_${r3_os_arch}_linux.tar.gz r3 config_template.json \t&& sed -i \"s/localhost/${r3_db_host}/g\" config_template.json \t&& sed -i \"s/443/80/g\" config_template.json \t&& chmod 755 r3 && chmod 644 config_template.json \t&& rm REI3_${r3_version}_${r3_os_arch}_linux.tar.gz" did not complete successfully: exit code: 2`

Test # 2

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
Linux gettech 6.1.0-13-amd64  Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

'=> ERROR [r3 5/5] RUN tar -xvf REI3_3.2_x64_linux.tar.gz r3 config_template.json  && sed -i "s/localhost/r3_db/g" config_template.json  && sed -i "s/443/80/g" conf  0.3s '

'> [r3 5/5] RUN tar -xvf REI3_3.2_x64_linux.tar.gz r3 config_template.json      && sed -i "s/localhost/r3_db/g" config_template.json    && sed -i "s/443/80/g" config_template.json        && chmod 755 r3 && chmod 644 config_template.json       && rm REI3_3.2_x64_linux.tar.gz:                                                                   
0.248 
0.248 gzip: stdin: not in gzip format
0.248 tar: Child returned status 1
0.248 tar: Error is not recoverable: exiting now
------
failed to solve: process "/bin/sh -c tar -xvf REI3_${r3_version}_${r3_os_arch}_linux.tar.gz r3 config_template.json \t&& sed -i \"s/localhost/${r3_db_host}/g\" config_template.json \t&& sed -i \"s/443/80/g\" config_template.json \t&& chmod 755 r3 && chmod 644 config_template.json \t&& rm REI3_${r3_version}_${r3_os_arch}_linux.tar.gz" did not complete successfully: exit code: 2'

A separate download wget https://rei3.de/downloads/REI3_3.2_x64_linux.tar.gz
Shows as an html doc type.

**Comment by r3-gabriel** [comment]
Sorry for the late reply, I was a bit swamped the last few days.

The issue appears to be that you are trying to setup a REI3 docker image with an unsupported version. As documented [here](https://github.com/r3-team/r3_docker), only versions that are available on our website (under `All releases`) can be used.

Currently, you can build with the following versions:
* 3.6 (the latest one and the default, if not overwritten)
* 3.5.4
* 3.4.3
* 3.3.5
* 3.2.5
* 3.1.3

**Comment by r3-gabriel** [comment]
No response, closing issue.
