### ISSUE TITLE
Postgres version mismatch on integrated backup

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3_docker#5]
The docker compose file uses the latest postgres version (v16) for the database server but the Dockerfile uses stable debian version with their current postgres-client package (v15). The backup with pg_dump fails with a version mismatch.

I fixed that in my Dockerfile by using these commands in RUN:
```
apt-get install -y postgresql-common
YES=true /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
apt-get postgresql-client-16
```

And in the docker compose file i set the postgres server image to a fixed version:
`image: postgres:16`

**Comment by r3-gabriel** [comment]
I have not had time to test it myself, but what you write makes sense.

I´ll take a stab at it soon. Thank you for the report.

**Comment by r3-gabriel** [comment]
Updated dockerfile and compose files to set a fixed os & DB server version to make sure postgres client utilities stay compatible.
